namespace Rhythmo.Shared.Ranking;

public sealed record ExerciseRankingDef(
	string Category,
	string NameFr,
	IReadOnlyList<string> PrimaryMuscles,
	IReadOnlyList<string> SecondaryMuscles,
	MeasurementType? MeasurementType,
	LoadMode LoadMode,
	StandardSource? Source,
	Comparability Comparability,
	string Confidence,
	double? R10Male70,
	double? R10Male100,
	double? R10Female60,
	double? R10Female90)
{
	public bool IsClassifying => PrimaryMuscles.Count > 0;
}

/// <summary>Métadonnées ranking V1, indexées par (catégorie, nom) alignés sur le seed MAUI.</summary>
public static class MuscleRankingCatalog
{
	public static IReadOnlyList<ExerciseRankingDef> All { get; } = Build();

	public static ExerciseRankingDef? Find(string category, string nameFr) =>
		All.FirstOrDefault(x => x.Category == category && x.NameFr == nameFr);

	private static IReadOnlyList<ExerciseRankingDef> Build() =>
	[
		// --- Pectoraux primary ---
		C("Pectoraux", "Développé incliné", [MuscleIds.UpperChest, MuscleIds.MidChest], [],
			MeasurementType.OneRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.High, "high",
			119, 160, 76, 97),
		C("Pectoraux", "Développé incliné haltères", [MuscleIds.UpperChest, MuscleIds.MidChest], [],
			MeasurementType.OneRm, LoadMode.PerDumbbell, StandardSource.StrengthLevel, Comparability.High, "high",
			56, 73, 35, 43),
		C("Pectoraux", "Développé couché barre", [MuscleIds.MidChest], [],
			MeasurementType.OneRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.High, "high",
			136, 179, 88, 111),
		C("Pectoraux", "Développé couché haltères", [MuscleIds.MidChest], [],
			MeasurementType.OneRm, LoadMode.PerDumbbell, StandardSource.StrengthLevel, Comparability.High, "high",
			62, 79, 38, 46),
		C("Pectoraux", "Développé décliné", [MuscleIds.MidChest], [],
			MeasurementType.OneRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.High, "high",
			146, 197, 95, 120),
		C("Pectoraux", "Développé décliné haltères", [MuscleIds.MidChest], [],
			MeasurementType.OneRm, LoadMode.PerDumbbell, StandardSource.StrengthLevel, Comparability.High, "high",
			63, 79, 42, 53),
		C("Pectoraux", "Chest press", [MuscleIds.MidChest], [],
			MeasurementType.OneRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.Medium, "medium",
			147, 181, 75, 85),
		C("Pectoraux", "Pec deck / Butterfly", [MuscleIds.MidChest], [],
			MeasurementType.TenRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.Low, "medium",
			139, 175, 74, 91),
		C("Pectoraux", "Écarté haltères", [MuscleIds.MidChest], [],
			MeasurementType.TenRm, LoadMode.PerDumbbell, StandardSource.StrengthLevel, Comparability.High, "high",
			43, 54, 23, 27),
		C("Pectoraux", "Écarté poulie", [MuscleIds.MidChest], [],
			MeasurementType.TenRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.Medium, "medium",
			77, 98, 43, 51),
		S("Pectoraux", "Écarté haltères incliné", [], [MuscleIds.UpperChest, MuscleIds.MidChest]),
		S("Pectoraux", "Écarté poulie incliné", [], [MuscleIds.UpperChest, MuscleIds.MidChest]),
		S("Pectoraux", "Écarté haltères décliné", [], [MuscleIds.MidChest]),
		S("Pectoraux", "Pompes", [], [MuscleIds.MidChest, MuscleIds.FrontDelt, MuscleIds.Triceps]),
		S("Pectoraux", "Dips", [], [MuscleIds.MidChest, MuscleIds.Triceps, MuscleIds.FrontDelt]),

		// --- Dos ---
		C("Dos", "Tractions lestées", [MuscleIds.Lats], [MuscleIds.Biceps, MuscleIds.Traps, MuscleIds.Rhomboids],
			MeasurementType.OneRm, LoadMode.AddedLoad, StandardSource.RhythmoV1Manual, Comparability.High, "medium",
			50, 70, 35, 50),
		S("Dos", "Tractions", [], [MuscleIds.Lats, MuscleIds.Biceps, MuscleIds.Traps, MuscleIds.Rhomboids]),
		C("Dos", "Tirage vertical prise serrée", [MuscleIds.Lats], [MuscleIds.Biceps],
			MeasurementType.FiveRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.Medium, "high",
			123, 150, 76, 88),
		C("Dos", "Tirage vertical", [MuscleIds.Lats], [MuscleIds.Biceps],
			MeasurementType.FiveRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.Medium, "high",
			123, 150, 76, 88),
		C("Dos", "Rowing barre", [MuscleIds.Lats, MuscleIds.Traps, MuscleIds.Rhomboids], [],
			MeasurementType.FiveRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.High, "high",
			127, 166, 78, 91),
		C("Dos", "Rowing haltère", [MuscleIds.Lats, MuscleIds.Traps, MuscleIds.Rhomboids], [],
			MeasurementType.FiveRm, LoadMode.PerDumbbell, StandardSource.StrengthLevel, Comparability.High, "high",
			69, 89, 38, 45),
		C("Dos", "Tirage horizontal", [MuscleIds.Lats, MuscleIds.Traps, MuscleIds.Rhomboids], [],
			MeasurementType.FiveRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.Medium, "high",
			128, 160, 79, 94),
		C("Dos", "Rowing poulie unilatéral", [MuscleIds.Lats, MuscleIds.Traps, MuscleIds.Rhomboids], [],
			MeasurementType.FiveRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.Medium, "medium",
			104, 127, 64, 72),
		C("Dos", "Pullover", [MuscleIds.Lats], [],
			MeasurementType.OneRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.Medium, "medium",
			91, 116, 51, 60),
		C("Dos", "Shrug barre", [MuscleIds.Traps], [],
			MeasurementType.FiveRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.High, "high",
			205, 274, 134, 170),
		C("Dos", "Shrug haltères", [MuscleIds.Traps], [],
			MeasurementType.FiveRm, LoadMode.PerDumbbell, StandardSource.StrengthLevel, Comparability.High, "high",
			77, 97, 38, 45),
		C("Dos", "Shrug machine", [MuscleIds.Traps], [],
			MeasurementType.FiveRm, LoadMode.Total, StandardSource.RhythmoEstimated, Comparability.Low, "low",
			249, 311, 162, 202),
		C("Dos", "Soulevé de terre", [MuscleIds.Erectors], [MuscleIds.Glutes, MuscleIds.Hamstrings, MuscleIds.Traps],
			MeasurementType.OneRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.High, "high",
			216, 279, 149, 180),
		C("Dos", "Extension lombaire machine", [MuscleIds.Erectors], [],
			MeasurementType.FiveRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.Medium, "medium",
			185, 219, 126, 143),
		S("Dos", "Rowing T-Bar", [], [MuscleIds.Lats, MuscleIds.Traps, MuscleIds.Rhomboids]),
		S("Dos", "Muscle-up", [], [MuscleIds.Lats, MuscleIds.Triceps]),
		S("Dos", "Landmine 180", [], []),

		// --- Épaules ---
		C("Épaules", "Développé militaire", [MuscleIds.FrontDelt], [],
			MeasurementType.FiveRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.High, "high",
			75, 100, 46, 57),
		C("Épaules", "Développé militaire haltères", [MuscleIds.FrontDelt], [],
			MeasurementType.FiveRm, LoadMode.PerDumbbell, StandardSource.StrengthLevel, Comparability.High, "high",
			41, 54, 23, 27),
		C("Épaules", "Shoulder press", [MuscleIds.FrontDelt], [],
			MeasurementType.FiveRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.Low, "low",
			112, 146, 57, 67),
		C("Épaules", "Élévations latérales", [MuscleIds.SideDelt], [],
			MeasurementType.TenRm, LoadMode.PerDumbbell, StandardSource.RhythmoV1Manual, Comparability.High, "medium",
			25, 30, 16, 19),
		C("Épaules", "Élévations latérales poulie", [MuscleIds.SideDelt], [],
			MeasurementType.TenRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.Medium, "medium",
			28, 33, 19, 21),
		C("Épaules", "Élévations latérales machine", [MuscleIds.SideDelt], [],
			MeasurementType.TenRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.Low, "medium",
			75, 98, 41, 48),
		C("Épaules", "Reverse pec deck", [MuscleIds.RearDelt], [],
			MeasurementType.TenRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.Medium, "medium",
			82, 104, 42, 50),
		C("Épaules", "Face pull", [MuscleIds.RearDelt], [MuscleIds.Traps, MuscleIds.Rhomboids],
			MeasurementType.FiveRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.Medium, "medium",
			75, 92, 56, 66),
		S("Épaules", "Oiseau", [], [MuscleIds.RearDelt]),
		S("Épaules", "Oiseau poulie", [], [MuscleIds.RearDelt]),
		S("Épaules", "Élévations frontales", [], [MuscleIds.FrontDelt]),
		S("Épaules", "Tirage menton", [], [MuscleIds.SideDelt, MuscleIds.Traps]),
		S("Épaules", "Arnold press", [], [MuscleIds.FrontDelt]),

		// --- Bras ---
		C("Biceps", "Curl barre", [MuscleIds.Biceps], [],
			MeasurementType.FiveRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.High, "high",
			63, 79, 40, 49),
		C("Biceps", "Curl haltères", [MuscleIds.Biceps], [],
			MeasurementType.FiveRm, LoadMode.PerDumbbell, StandardSource.StrengthLevel, Comparability.High, "high",
			33, 41, 21, 25),
		C("Biceps", "Curl pupitre", [MuscleIds.Biceps], [],
			MeasurementType.FiveRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.High, "high",
			62, 76, 39, 49),
		S("Biceps", "Curl poulie", [], [MuscleIds.Biceps]),
		S("Biceps", "Curl incliné", [], [MuscleIds.Biceps]),
		S("Biceps", "Curl marteau", [], [MuscleIds.Biceps]),
		C("Triceps", "Extension poulie", [MuscleIds.Triceps], [],
			MeasurementType.FiveRm, LoadMode.Total, StandardSource.RhythmoV1Manual, Comparability.Medium, "medium",
			65, 95, 50, 80),
		C("Triceps", "Pushdown corde", [MuscleIds.Triceps], [],
			MeasurementType.FiveRm, LoadMode.Total, StandardSource.RhythmoV1Manual, Comparability.Medium, "medium",
			60, 90, 45, 75),
		C("Triceps", "Extension overhead poulie", [MuscleIds.Triceps], [],
			MeasurementType.FiveRm, LoadMode.Total, StandardSource.RhythmoV1Manual, Comparability.Medium, "medium",
			55, 85, 40, 70),
		S("Triceps", "Barre au front", [], [MuscleIds.Triceps]),
		S("Triceps", "Dips", [], [MuscleIds.Triceps, MuscleIds.MidChest]),
		S("Triceps", "Extension haltère derrière la tête", [], [MuscleIds.Triceps]),
		S("Triceps", "Développé serré", [], [MuscleIds.Triceps, MuscleIds.MidChest]),

		// --- Abdominaux ---
		C("Abdominaux", "Crunch poulie", [MuscleIds.AbsMuscle], [],
			MeasurementType.TenRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.Medium, "high",
			96, 107, 71, 82),
		C("Abdominaux", "Crunch machine", [MuscleIds.AbsMuscle], [],
			MeasurementType.TenRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.Low, "medium",
			109, 133, 67, 76),
		C("Abdominaux", "Crunch décliné lesté", [MuscleIds.AbsMuscle], [],
			MeasurementType.OneRm, LoadMode.AddedLoad, StandardSource.RhythmoV1Manual, Comparability.Medium, "medium",
			80, 110, 60, 90),
		C("Abdominaux", "Reverse crunch lesté", [MuscleIds.AbsMuscle], [],
			MeasurementType.OneRm, LoadMode.AddedLoad, StandardSource.RhythmoV1Manual, Comparability.Low, "low",
			90, 120, 70, 100),
		S("Abdominaux", "Crunch", [], [MuscleIds.AbsMuscle]),
		S("Abdominaux", "Relevés de jambes", [], [MuscleIds.AbsMuscle]),
		S("Abdominaux", "Relevés de jambes suspendu", [], [MuscleIds.AbsMuscle]),
		S("Abdominaux", "Gainage", [], [MuscleIds.AbsMuscle]),
		S("Abdominaux", "Ab wheel", [], [MuscleIds.AbsMuscle]),
		S("Abdominaux", "Russian twist", [], [MuscleIds.AbsMuscle]),
		S("Abdominaux", "Mountain climbers", [], [MuscleIds.AbsMuscle]),
		S("Abdominaux", "Planche latérale", [], [MuscleIds.AbsMuscle]),
		S("Abdominaux", "Hollow body hold", [], [MuscleIds.AbsMuscle]),
		S("Abdominaux", "Flexion latérale au banc", [], [MuscleIds.AbsMuscle]),

		// --- Jambes ---
		C("Jambes — Quadriceps", "Squat", [MuscleIds.Quads, MuscleIds.Glutes], [],
			MeasurementType.OneRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.High, "high",
			185, 244, 129, 158),
		C("Jambes — Quadriceps", "Hack squat", [MuscleIds.Quads], [],
			MeasurementType.OneRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.Medium, "high",
			257, 321, 190, 221),
		C("Jambes — Quadriceps", "Presse à cuisses", [MuscleIds.Quads], [],
			MeasurementType.OneRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.Medium, "high",
			359, 460, 277, 337),
		C("Jambes — Quadriceps", "Leg extension", [MuscleIds.Quads], [],
			MeasurementType.TenRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.Medium, "high",
			127, 151, 86, 98),
		C("Jambes — Quadriceps", "Bulgarian split squat", [MuscleIds.Quads, MuscleIds.Glutes], [],
			MeasurementType.OneRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.High, "high",
			128, 170, 77, 90),
		C("Ischios / Fessiers", "Fentes marchées", [MuscleIds.Quads, MuscleIds.Glutes], [],
			MeasurementType.OneRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.High, "high",
			110, 139, 71, 75),
		C("Ischios / Fessiers", "Soulevé de terre roumain", [MuscleIds.Hamstrings, MuscleIds.Glutes], [],
			MeasurementType.OneRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.High, "high",
			184, 238, 116, 132),
		C("Ischios / Fessiers", "Leg curl", [MuscleIds.Hamstrings], [],
			MeasurementType.TenRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.Medium, "high",
			80, 100, 50, 59),
		C("Ischios / Fessiers", "Hip thrust", [MuscleIds.Glutes], [],
			MeasurementType.OneRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.High, "high",
			257, 335, 199, 226),
		C("Mollets", "Mollets machine", [MuscleIds.Calves], [],
			MeasurementType.TenRm, LoadMode.Total, StandardSource.StrengthLevel, Comparability.Medium, "high",
			131, 160, 110, 128),
		S("Jambes — Quadriceps", "Front squat", [], [MuscleIds.Quads]),
		S("Jambes — Quadriceps", "Fentes", [], [MuscleIds.Quads, MuscleIds.Glutes]),
		S("Jambes — Quadriceps", "Sissy squat", [], [MuscleIds.Quads]),
		S("Ischios / Fessiers", "Good morning", [], [MuscleIds.Hamstrings, MuscleIds.Erectors]),
		S("Ischios / Fessiers", "Glute bridge", [], [MuscleIds.Glutes]),
		S("Ischios / Fessiers", "Kickback poulie", [], [MuscleIds.Glutes]),
		S("Mollets", "Mollets smith", [], [MuscleIds.Calves]),
		S("Mollets", "Mollets à la presse", [], [MuscleIds.Calves]),
		S("Jambes — Quadriceps", "Adducteur machine", [], [MuscleIds.Adductors]),
		S("Jambes — Quadriceps", "Adduction hanche poulie", [], [MuscleIds.Adductors])
	];

	private static ExerciseRankingDef C(
		string category,
		string name,
		string[] primary,
		string[] secondary,
		MeasurementType measurement,
		LoadMode load,
		StandardSource source,
		Comparability comparability,
		string confidence,
		double m70, double m100, double f60, double f90) =>
		new(category, name, primary, secondary, measurement, load, source, comparability, confidence,
			m70, m100, f60, f90);

	private static ExerciseRankingDef S(string category, string name, string[] primary, string[] secondary) =>
		new(category, name, primary, secondary, null, LoadMode.Total, null, Comparability.Medium, "n/a",
			null, null, null, null);
}
